import Head from 'next/head'
import { useState } from 'react'
import type { MouseEventHandler } from 'react'
import { Header, Footer, LazyImage, CustomButton } from '@/components'
import { API } from '@/services'
import { ImageItems } from '@/types'

export default function Home() {
  const api = API()
  const [images, setImages] = useState<Array<ImageItems>>([])

  const handleAddImage: MouseEventHandler<HTMLButtonElement> = (event) => {
    const generateID = (item: Array<ImageItems>): number => {
      let id: number = 0
      do {
        id = Math.floor(Math.random() * 1000000)
      } while (item.some((obj) => obj.id === id))
      return id
    }
    const auxImg: ImageItems = { id: generateID(images), url: api }

    setImages([...images, auxImg])
  }

  return (
    <>
      <Head>
        <title>Fox LazyLoad</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🦊</text></svg>"
        />
      </Head>
      <div className="flex flex-col min-h-screen">
        <Header />
        <main>
          <div className="relative isolate px-6 pt-14 lg:px-8">
            <div className="mx-auto max-w-2xl lg:max-w-3xl py-32 sm:py-42 lg:py-32">
              <div className="text-center">
                <h1 className="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">
                  Fox Lazy Image
                </h1>
                <p className="mt-4">
                  The added images will not be downloaded until they are visible
                  on the screen
                </p>
                <p className="mt-4">✨✨</p>
                <div className="mt-10 flex items-center justify-center gap-x-6">
                  <CustomButton
                    onClick={handleAddImage}
                    className="rounded-md bg-gray-700 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-gray-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-gray-700"
                  >
                    Add new fox
                  </CustomButton>
                </div>
                <div className="grid lg:grid-cols-4 md:grid-cols-2 py-4">
                  {images.map(({ id, url }, index) => (
                    <div key={id} className="p-4">
                      <LazyImage
                        src={url}
                        onLazyLoad={(img) => {
                          console.log(`Image #${index + 1} cargada. Nodo:`, img)
                        }}
                      />
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </main>
        <Footer />
      </div>
    </>
  )
}
